{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "response time average request per minute (User)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A * 60", "type": "math" }
   ]
  },
  {
   "title": "response time average request per minute (product)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(response_time_seconds_count{handler_name=\"GetProduct\"}[1m])",
     "legendFormat": "__auto"
    },
    { "expression": "$A * 60", "type": "math" }
   ]
  },
  {
   "title": "Request_per_minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expression": "($A + $B) * 60", "type": "math" }
   ]
  },
  {
   "title": "active average request per minute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A * 60", "type": "math" }
   ]
  }
 ]
}